# Generated by Django 2.2.5 on 2023-04-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.BooleanField(default=False),
        ),
    ]
